name: Validate package
on:
  push:
  pull_request:
permissions:
  contents: read
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
      - name: Test installation and registry
        run: python3 -m unittest discover -s tests -v
      - name: Check whitespace
        run: git diff --check HEAD
